var d1 = [
    ["id", "position", "label", "name", "presentation"],
    ["1", "9", "P06", "Dice lo que piensa y siente de manera asertiva", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["3", "10", "P07", "Sabe escuchar", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["4", "11", "P08", "Expone sus ideas de manera clara", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["5", "12", "P09", "Desarrolla documentos claros y concisos, logrando comunicar efectivamente el mensaje", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["6", "13", "P10", "Comparte información", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["7", "14", "P11", "Mantiene informados a otros respecto a su trabajo o situaciones importants", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["8", "15", "P12", "Maneja adecuadamente conversaciones delicadas", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["9", "16", "P13", "Proporciona y solicita retroalimentación", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["10", "17", "P14", "Se comunica con propiedad y respeto con los diferents niveles jerárquicos con quienes interactúa", "r>>>>>0####Nunca|33####Rara Vez|-1####Desconozco|67####Casi Siempre|100####Siempre<<<<<1"],
    ["12", "19", "P15", "Comparte ideas, información y/o conocimientos con los miembros de su equipo o con otras áreas", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["13", "20", "P16", "Ayuda a otros en lo necesario cuando se le pide apoyo", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["14", "21", "P17", "Es responsable con la(s) tareas que le corresponden", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["15", "22", "P18", "Evita la intriga y es respetuoso", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["16", "23", "P19", "Sabe escuchar y toma en cuenta las opiniones de los demas", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["17", "24", "P20", "Promueve y alienta con el ejemplo, el trabajo en equipo", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["18", "25", "P21", "Es un apersona en quien se puede confiar", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["19", "26", "P22", "Las personas lo quieren en sus equipos de trabajo", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["20", "27", "P23", "Comparte los créditos y los errores del equipo", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["21", "28", "P24", "Tiene buenas relaciones interpersonales", "r>>>>>Nunca |Rara Vez |Desconozco |Casi Siempre |Siempre<<<<<1"],
    ["22", "3", "P01", "Site", "d>>>>>AGA |KROMA |CRISOL |TEPEXPAN"],
    ["26", "4", "P02", "Cargo", "d>>>>>Director o Sub director |Gerente o Sub Gerente |Jefe, Supervisor o Coordinador |Administrativos |Técnicos |Operativo"],
    ["27", "5", "P03", "Sexo", "d>>>>>Masculino |Femenino"],
    ["28", "6", "P04", "Grado Académico", "d>>>>>Enseñanza Media o Inferior |Universidad Incompleta |Universidad Completa |Posgrado"],
    ["29", "7", "P05", "Edad", "d>>>>>18 a 20 años |21 a 25 años |26 a 34 años |35 a 44 años |45 a 54 años |55 años en adelante"]
];
var d2 = [
    ["completed", "item", "value"],
    ["1", "1", "2"],
    ["1", "3", "4"],
    ["1", "4", "3"],
    ["1", "5", "5"],
    ["1", "6", "1"],
    ["1", "7", "4"],
    ["1", "8", "3"],
    ["1", "9", "5"],
    ["1", "10", "4"],
    ["1", "12", "1"],
    ["1", "13", "5"],
    ["1", "14", "2"],
    ["1", "15", "4"],
    ["1", "16", "3"],
    ["1", "17", "3"],
    ["1", "18", "2"],
    ["1", "19", "4"],
    ["1", "20", "1"],
    ["1", "21", "5"],
    ["1", "22", "2"],
    ["1", "26", "1"],
    ["1", "27", "1"],
    ["1", "28", "2"],
    ["1", "29", "5"],
    ["2", "1", "1"],
    ["2", "3", "2"],
    ["2", "4", "3"],
    ["2", "5", "4"],
    ["2", "6", "5"],
    ["2", "7", "4"],
    ["2", "8", "3"],
    ["2", "9", "2"],
    ["2", "10", "3"],
    ["2", "12", "1"],
    ["2", "13", "3"],
    ["2", "14", "4"],
    ["2", "15", "5"],
    ["2", "16", "4"],
    ["2", "17", "3"],
    ["2", "18", "2"],
    ["2", "19", "1"],
    ["2", "20", "2"],
    ["2", "21", "3"],
    ["2", "22", "4"],
    ["2", "26", "4"],
    ["2", "27", "2"],
    ["2", "28", "4"],
    ["2", "29", "3"]
];